version: 1.0.{build}.{branch}

build: off

matrix:
  fast_finish: true

# We always use a 64-bit machine, but can build x86 distributions
# with the PYTHON_ARCH variable.
platform:
  - x64

environment:

  global:

    MINGW_32: C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin
    MINGW_64: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin
    DEFAULT_PYTHON: "C:\\Python37-x64"

  matrix:

    # See: https://www.appveyor.com/docs/installed-software/#python

    - PYTHON_ARCH: "32"
      NOX_SESSION: "unit(py='2.7')"

    - PYTHON_ARCH: "64"
      NOX_SESSION: "unit(py='2.7')"

    - PYTHON_ARCH: "32"
      NOX_SESSION: "unit(py='3.5')"

    - PYTHON_ARCH: "64"
      NOX_SESSION: "unit(py='3.5')"

    - PYTHON_ARCH: "32"
      NOX_SESSION: "unit(py='3.6')"

    - PYTHON_ARCH: "64"
      NOX_SESSION: "unit(py='3.6')"

    - PYTHON_ARCH: "32"
      NOX_SESSION: "unit(py='3.7')"

    - PYTHON_ARCH: "64"
      NOX_SESSION: "cover"

    - PYTHON_ARCH: "64"
      NOX_SESSION: "functional(py='3.7')"

    - PYTHON_ARCH: "64"
      NOX_SESSION: "doctest"

    - PYTHON_ARCH: "64"
      NOX_SESSION: "check_journal(machine='appveyor')"

install:
  - cmd: echo "Filesystem root:"
  - dir C:\

  - echo "Installed SDKs:"
  - dir "C:/Program Files/Microsoft SDKs/Windows"

  # Make 64-bit Python 3.7 the "default" Python.
  - "SET PATH=%DEFAULT_PYTHON%;%DEFAULT_PYTHON%\\Scripts;%PATH%"

  # Append MinGW to the PATH of this build so ``gfortran`` is visible
  # to ``numpy.distutils``.
  - ps: |
      $PYTHON_ARCH = $env:PYTHON_ARCH
      If ($PYTHON_ARCH -eq 32) {
          $MINGW = $env:MINGW_32
      } Else {
          $MINGW = $env:MINGW_64
      }
      $env:Path += ";$MINGW"

  # Packaging requirements
  - python -m pip install --upgrade pip setuptools
  - python -m pip install --upgrade wheel

  # Install the build dependencies of the project.
  - python -m pip install --upgrade "nox-automation == 0.19.1"

test_script:
  - "nox.exe -s \"%NOX_SESSION%\""
