version: 1.0.{build}.{branch}

build: off

environment:

  global:

    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    # NOTE: We don't use this (for now).
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\obvci_appveyor_python_build_env.cmd"

  matrix:

    # Pre-installed Miniconda versions, which AppVeyor may upgrade to
    # a later point release.
    # See: https://www.appveyor.com/docs/installed-software/#python
    # Borrowed from conda-forge recipes.

    - TARGET_ARCH: x86
      CONDA_PY: 27
      CONDA_INSTALL_LOCN: C:\\Miniconda

    - TARGET_ARCH: x64
      CONDA_PY: 27
      CONDA_INSTALL_LOCN: C:\\Miniconda-x64

    - TARGET_ARCH: x86
      CONDA_PY: 34
      CONDA_INSTALL_LOCN: C:\\Miniconda3

    - TARGET_ARCH: x64
      CONDA_PY: 34
      CONDA_INSTALL_LOCN: C:\\Miniconda3-x64

    - TARGET_ARCH: x86
      CONDA_PY: 35
      CONDA_INSTALL_LOCN: C:\\Miniconda35

    - TARGET_ARCH: x64
      CONDA_PY: 35
      CONDA_INSTALL_LOCN: C:\\Miniconda35-x64

    - TARGET_ARCH: x86
      CONDA_PY: 36
      CONDA_INSTALL_LOCN: C:\\Miniconda

    - TARGET_ARCH: x64
      CONDA_PY: 36
      CONDA_INSTALL_LOCN: C:\\Miniconda-x64

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
      https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
      Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }

  # Update paths for ``conda``.
  - cmd: set "OLDPATH=%PATH%"
  - cmd: set "PATH=%CONDA_INSTALL_LOCN%\\Scripts;%CONDA_INSTALL_LOCN%\\Library\\bin;%PATH%"

  # Update ``conda`` settings.
  - cmd: conda config --set show_channel_urls true
  - cmd: conda config --add channels conda-forge

  # Sleuth: ``conda`` install info.
  - cmd: conda --version
  - cmd: conda info --envs
  - cmd: conda info

  # Actually activate ``conda``.
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: set PYTHONUNBUFFERED=1

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Install (hardcoded) dependencies for ``bezier``.
  - cmd: conda install --yes enum34 matplotlib numpy six
