language: generic
os: osx

matrix:
  include:
    - os: osx
      language: generic
      env:
        - PY_VERSION=2.7
    - os: osx
      language: generic
      env:
        - PY_VERSION=3.6
    - os: osx
      language: generic
      env:
        - PY_VERSION=3.7

install:
  - source scripts/macos/travis-setup.sh

script:
  - scripts/macos/test.sh
