language: generic
os: osx

matrix:
  include:
    - os: osx
      language: generic
      env:
        - PY_VERSION=2.7
    - os: osx
      language: generic
      env:
        - PY_VERSION=3.5
    - os: osx
      language: generic
      env:
        - PY_VERSION=3.6

install:
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - source scripts/osx/travis-setup.sh

script:
  - scripts/osx/travis-test.sh
