---
language: generic
os: osx
osx_image: xcode12.2 # This is latest as of February 12, 2021

branches:
  only:
    - main

addons:
  homebrew:
    packages:
      - gcc # For `gfortran`

matrix:
  include:
    - os: osx
      language: generic
      env:
        - PY_VERSION=3.7
        - VIRTUALENV_NO_DOWNLOAD=true
    - os: osx
      language: generic
      env:
        - PY_VERSION=3.8
        - VIRTUALENV_NO_DOWNLOAD=true
    - os: osx
      language: generic
      env:
        - PY_VERSION=3.9
        - VIRTUALENV_NO_DOWNLOAD=true

install:
  - source scripts/macos/travis-setup.sh

script:
  - scripts/macos/test.sh
