---
version: 2
jobs:
  build:
    working_directory: /var/code/bezier/
    docker:
      - image: dhermes/bezier:latest
    environment:
      MATPLOTLIBRC: tests
    steps:
      - checkout
      - run:
          name: Check that all Cython generated files have been updated
          command: nox -s "update_generated(check=True)"
      - run:
          name: Unit tests in Python 3.5
          command: nox -s "unit_tests(python_version='3.5')"
      - run:
          name: Unit tests in Python 3.6
          command: nox -s "unit_tests(python_version='3.6')"
      - run:
          name: Unit tests AND line coverage in Python 2.7
          command: nox -s cover
      - run:
          name: Build docs
          command: nox -s docs
      - run:
          name: Run all doctests
          command: nox -s doctest
      - run:
          name: Lint code for style issues
          command: nox -s lint
      - run:
          name: Functional tests in Python 3.6
          command: nox -s "functional(python_version='3.6')"
      - run:
          name: Run memory benchmark
          command: nox -s "benchmark(target='memory')"
      - run:
          name: Run time benchmark
          command: nox -s "benchmark(target='time')"
      - deploy:
          name: Upload coverage to coveralls
          command: |
            .nox/cover/bin/pip install coveralls
            .nox/cover/bin/coveralls
